fail-on-severity: low
fail-on-scopes:
  - runtime
  - development
  - unknown
vulnerability-check: true
license-check: true
warn-only: false
comment-summary-in-pr: never
show-openssf-scorecard: true
warn-on-openssf-scorecard-level: 5
