# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.1
_src_path: gh:stelewis/copier-uv-template
author_email: 31178492+stelewis@users.noreply.github.com
author_name: Stephen Lewis
description: A Python test quality toolkit written in Rust
github_codeowner: '@stelewis'
github_repository: stelewis/tq
package_name: tq
project_name: Test Quality Toolkit
project_slug: tq
