version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - addopts
  - agentic
  - Antipatterns
  - arcname
  - asyncio
  - auxilary
  - capsys
  - chdir
  - CLI
  - Cloudant
  - commitizen
  - Commitizen
  - configfile
  - conftest
  - dataclasses
  - docstrings
  - duplicative
  - elif
  - filterwarnings
  - frontmatter
  - Frontmatter
  - getcwd
  - Hmac
  - invokable
  - isinstance
  - kwargs
  - mapfile
  - mnda
  - monkeypatch
  - msgfile
  - negotiables
  - OOXML
  - overengineered
  - overengineering
  - pathlib
  - pdfplumber
  - pipefail
  - prek
  - pycache
  - pydantic
  - pydocstyle
  - pylint
  - Pypi
  - pyproject
  - pytest
  - pyyaml
  - reprioritize
  - rtype
  - sdist
  - setattr
  - Sigstore
  - Stringly
  - testpaths
  - theo
  - tqlint
  - venv
  - zipf
ignoreWords: []
import: []
